# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-referral-api

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Globals:
  Function:
    Tags:
      Environment: !Ref Environment
      Name: SAM-referral
    Timeout: 3
    MemorySize: 128
Parameters:
  Environment:
    Type: String
    Description: SamTesting
    Default: dev
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-all-items.js
  ReferralTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: userId
        Type: String
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  referralFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/Functions/ReferralServices/
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        getReferralCode:
          Type: Api
          Properties:
            Path: /users/referral/get/{userId}
            Method: get
        replaceReferralCode:
          Type: Api
          Properties:
            Path: /users/referral/update/{userId}
            Method: put
        increaseReferralCount:
          Type: Api
          Properties:
            Path: /users/referral/{referralCode}
            Method: post
      Environment:
        Variables:
          REFERRAL_TABLE: !Ref ReferralTable
          REFERRAL_TABLE_ARN: !GetAtt ReferralTable.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ReferralTable
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
